Feature/78
MetaCell/geppetto-NeuroSCAN pull request #103
Opened 2021-06-09 09:48 UTC by afonsobspinto

closes #78 

Creates 3 common parsers (spreadsheet parser, filename parser, and web parser).
Each directory/entity creates a parser that makes, most of the time, use of the common parsers (by creating a configuration file) and glues everything together with custom logic.

Parsed files available [here](https://drive.google.com/drive/u/1/folders/1QTGEV6zXWYzGIqgbUSCN1MJqyUd2Ksuu)

Data questions available [here](https://docs.google.com/document/d/1OJYHyf9WgdIbkf0_wFBhm7eAkFHnQ8sKk2eoIsd8kFE/edit) (I think all of them are already being handled by Jerry)

2021-06-09 16:32 UTC, lrebscher commented on ingestion/parsers/common/utils.py
> +def get_args():
this method is not being used, want to keep it to support cli use or remove it?

2021-06-09 16:32 UTC, lrebscher commented on ingestion/parsers/common/web_parser.py
> +from bs4 import BeautifulSoup
not listed in requirements.txt

2021-06-09 16:52 UTC, lrebscher commented on ingestion/parsers/common/data_exporter.py
> +  def __init__(self, data):
your formatting doesn't conform to PEP-8, not so important for these scripts but better configure it accordingly

2021-06-09 16:55 UTC, lrebscher requested changes
very nice 👍 

it won't close the issue though since we need to do more adjustments once we've seen the complete dataset and folder structure

2021-06-09 17:05 UTC, afonsobspinto commented
From @lrebscher :
1. in the parsed data I see that you merge all pre objs matching e.g. AIBR-DVC. But there exist multiple synapses between AIBR-DVC and each one will be its own instance/row. We only merge the different stages/timepoints of a neuron into one row (if that is possible)
2. Noelle confirmed that they are dyadic and triadic synapses which just means that synapse is a 1:m relationship (1-pre to m-post). This has the implication that the “post” column will become a list of neurons
3. I’m now not so sure anymore if there is a matching pair of pre and post obj for each synapse… since we don’t have the data for it yet, this can wait, but I need to get this confirmed by Noelle. Could be that there are no pairs and every obj file becomes its own synapse instance.

2021-08-03 11:19 UTC, afonsobspinto commented
New parsed files available [here](https://drive.google.com/drive/u/1/folders/1UOaP5HUfUieZ8IgVeLqw4Srf9RbbYOVM)

[id_mapper.csv](https://github.com/MetaCell/geppetto-NeuroSCAN/files/6923606/id_mapper.csv) (promoter name -> wormbase id)

CSVs need to have well-defined headers (some were missing f.e. DCR_PromoterPipeline_Revised2021_Updated.xlsx). 
Sheet names must be consistent between files.

CPhate parser does not use the generic pipeline strategy but rather a custom script (needs to be adapted for multiple folders, delayed for when more data arrives)

Will add documentation for the parser later this week.

2021-08-03 18:26 UTC, lrebscher commented on ingestion/parsers/common/tests.py
> +import unittest
thx for the test 👍

2021-08-05 13:29 UTC, lrebscher commented on ingestion/parsers/promoters/parser.py
> +# from ingestion.parsers.common.config import Config
what about this commented code?

2021-08-05 13:51 UTC, lrebscher commented
- add a minimal [setup.py](https://docs.python.org/3/distutils/setupscript.html#writing-the-setup-script) to ingestion folder so that one can install & run this without having to modify sys.path, IntelliJ does this automatically for you but if you run a parser from the CLI it won't be aware of the `ingestion` module. For that you better add another `ingestion` folder that will contain the source code, so `ingestion/ingestion/parser` and `ingestion/setup.py`

- it's a flexible setup but at the same time it's also quite complex compared to writing a specific parser for each entity. As you mentioned we need to add some documentation here, a general how to use and also code documentation, e.g. of the pipeline syntax and filename config

2021-08-09 06:43 UTC, lrebscher commented
we will handle `setup.py` in a different PR

2021-08-09 06:43 UTC, merged