#189 Refactor tooltip for the canvas, so the canvas is not redraw everytime the tooltip appears.
MetaCell/geppetto-NeuroSCAN pull request #190
Opened 2021-11-04 22:41 UTC by jrmartin

2021-11-05 07:28 UTC, zsinnema requested changes
@jrmartin this solution has not the same functionality as the original in dev.
e.g. when you move your move after a hover the tooltip moves with your mouse position.
your solution doesn't do that

please fix

2021-11-05 07:41 UTC, zsinnema commented
btw I do agree on the solution since it renders less components, that's cool!

2021-11-05 21:30 UTC, jrmartin commented
Dario fixed this with this PR https://github.com/MetaCell/geppetto-meta/pull/193, this PR no longer needed.

2021-11-08 12:00 UTC, zsinnema approved these changes

2021-11-08 12:01 UTC, merged